export const MAIN_CONTAINER = 'MAIN_CONTAINER';
export const LOAD_GALLERY = 'LOAD_GALLERY';
export const SET_SERVICES_STATE ='SET_SERVICES_STATE';
export const SET_BANNER_STATE ='SET_BANNER_STATE';


export const SET_BODY_STATE = 'SET_BODY_STATE';
export const SET_LANDING = 'SET_LANDING';